spring:
  datasource:
    url: jdbc:postgresql://db:5432/evcoordinator
    driverClassName: org.postgresql.Driver
    username: postgres-user
    password: postgres-pass
  liquibase:
    drop-first: true
  jooq:
    sql-dialect: Postgres
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: evcoordinator
            authorization-grant-type: authorization_code
            scope:
              - openid
        provider:
          keycloak:
            issuer-uri: http://0.0.0.0:8080/realms/evcoordinator
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://0.0.0.0:8080/realms/evcoordinator
springdoc:
  swagger-ui:
    path: /api-docs
logging:
  level:
    root: info
