spring:
  datasource:
    url: jdbc:postgresql://db:5432/evcoordinator
    driverClassName: org.postgresql.Driver
    username: postgres-user
    password: postgres-pass
  liquibase:
    drop-first: true
  jooq:
    sql-dialect: Postgres
springdoc:
  swagger-ui:
    path: /api-docs
logging:
  level:
    root: info
