version: '3.8'

services:

  api:
    container_name: api
    image: 'api:latest'
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: db
    image: 'postgres:15.0-alpine3.16'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=evcoordinator --username=postgres-user"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=evcoordinator
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-pass