services:

  api:
    container_name: evcoordinator-api
    image: 'api:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - bricthentic_default
      - evcoordinator_default

  db:
    container_name: evcoordinator-db
    image: 'postgres:15.0-alpine3.16'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname=evcoordinator --username=postgres-user"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_DB=evcoordinator
      - POSTGRES_USER=postgres-user
      - POSTGRES_PASSWORD=postgres-pass
# Uncomment this to allow for direct DB access.
#    ports:
#      - "5432:5432"
    expose:
      - 5432
    networks:
      - evcoordinator_default

networks:
  bricthentic_default:
    driver: bridge
    name: bricthentic_default
    external: true
  evcoordinator_default:
    driver: bridge
    name: evcoordinator_default